# Generated by Django 4.2.2 on 2023-06-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('role', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
